# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import APIDataframe_pb2 as APIDataframe__pb2


class APIDataframeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Min = channel.unary_unary(
                '/APIDataframe/Min',
                request_serializer=APIDataframe__pb2.Result.SerializeToString,
                response_deserializer=APIDataframe__pb2.Result.FromString,
                )


class APIDataframeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Min(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_APIDataframeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Min': grpc.unary_unary_rpc_method_handler(
                    servicer.Min,
                    request_deserializer=APIDataframe__pb2.Result.FromString,
                    response_serializer=APIDataframe__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'APIDataframe', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class APIDataframe(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Min(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/APIDataframe/Min',
            APIDataframe__pb2.Result.SerializeToString,
            APIDataframe__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
